# 基本信息
title: Nova 的技术博客
email: nova_xyz@163.com
author: Nova
description: >-
  开发学习笔记。
baseurl: ""
url: "https://znovadev.github.io"

# 社交链接
twitter_username: novadev
github_username:  znovadev

# 主题（使用远程主题）
theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# 分页
paginate: 5
paginate_path: /page:num/

# Markdown 配置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# 永久链接
permalink: /:year/:month/:day/:title/

# 时区
timezone: Asia/Shanghai

# 默认值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Disqus 评论（可选）
disqus:
  shortname: znovadev
